global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
# — “first.rules”
# — “second.rules”
scrape_configs:
  - job_name: backend
    metrics_path: api/metrics
    static_configs:
      - targets:
          - poisonsvb.com
  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
          - poisonsvb.com:9100
          - node-exporter:9100
